export const PER_CONTINENT_REQUEST = "PER_CONTINENT_REQUEST";
export const PER_CONTINENT_SUCCESS = "PER_CONTINENT_SUCCESS";
export const PER_CONTINENT_FAIL = "PER_CONTINENT_FAIL";

export const COUNTRIES_REQUEST = "COUNTRIES_REQUEST";
export const COUNTRIES_SUCCESS = "COUNTRIES_SUCCESS";
export const COUNTRIES_FAIL = "COUNTRIES_FAIL";
